export const usageResourcesMap: Record<string, string[]> = {
    'azure-ad': ['azuread-seats-total'],
    dynamics365: ['dynamics365-seats-total'],
    gsuite: ['gsuite-seats-total'],
    'o365-admin': ['o365-admin-seats-total'],
    powerbi: ['powerbi-seats-total'],
    sforce: ['sforce-seats-total'],
    zendesk: ['zendesk-seats-total'],
    'azure-do': ['azuredo-seats-total'],
    'confluence-connector': ['confluence-seats-total'],
    'jira-connector': ['jira-seats-total'],
    'bamboohr-connector': ['bamboohr-seats-total'],
    'docusign-connector': ['docusign-seats-total'],
    'okta-connector': ['okta-seats-total'],
    'miro-connector': ['miro-seats-total']
};

export const connectorDisplayNames: Record<string, string> = {
    'azure-ad': 'Entra ID',
    'azure-do': 'Azure DevOps',
    dynamics365: 'Power Platform / Dynamics 365',
    gsuite: 'Google Workspace',
    'o365-admin': 'Microsoft 365',
    powerbi: 'Power BI',
    sforce: 'Salesforce',
    zendesk: 'Zendesk',
    'confluence-connector': 'Confluence',
    'jira-connector': 'Jira',
    'bamboohr-connector': 'BambooHR',
    'docusign-connector': 'DocuSign',
    'okta-connector': 'Okta',
    'miro-connector': 'Miro'
};

export const resourcesTableTranslations: Record<string, string> = {
    'azuread-seats-total': 'Entra ID (Advanced)',
    'azuread-users': 'Entra ID (Advanced)',
    'azuredo-seats-total': 'Azure DevOps',
    'azuredo-users': 'Azure DevOps',
    'dynamics365-seats-total': 'Power Platform / Dynamics 365 Total',
    'dynamics365-users': 'Dynamics 365 Full',
    'dynamics365-users-light': 'Dynamics 365 Light',
    'power-plat-total': 'Power Platform Total',
    'power-plat-full': 'Power Platform Full',
    'power-plat-automate-full': 'Power Platform Automate Full',
    'power-plat-pages-full': 'Power Platform Pages Full',
    'power-plat-pages': 'Power Platform Pages',
    'power-plat-automate': 'Power Platform Automate',
    'power-plat-apps-full': 'Power Platform Apps Full',
    'power-plat-apps': 'Power Platform Apps',
    'gsuite-seats-total': 'Google Workspace',
    'gw-quadseats-total': 'Google Workspace',
    'gw-quadseats-education': 'Google Workspace Education',
    'gw-quadseats-full': 'Google Workspace Full',
    'gw-quadseats-light': 'Google Workspace Light',
    'm365-quadseats-total': 'Microsoft 365 Total',
    'm365-quadseats-full': 'Microsoft 365 Full',
    'm365-quadseats-light': 'Microsoft 365 Light',
    'm365-quadseats-faculty': 'Microsoft 365 Faculty',
    'm365-quadseats-student': 'Microsoft 365 Student',
    'm365-mailboxonedrive-total': 'Microsoft 365 Total',
    'm365-mailboxonedrive-full': 'Microsoft 365 Full',
    'm365-mailboxonedrive-light': 'Microsoft 365 Light',
    'm365-mailboxonedrive-student': 'Microsoft 365 Student',
    'm365-mailboxonedrive-faculty': 'Microsoft 365 Faculty',
    'entraid-users-total': 'Entra ID Total',
    'entraid-users-full': 'Entra ID Full',
    'entraid-users-light': 'Entra ID Light',
    'entraid-users-faculty': 'Entra ID Faculty',
    'entraid-users-student': 'Entra ID Student',
    'o365-admin-seats-total': 'Microsoft 365 Total',
    'powerbi-seats-total': 'Power BI Total',
    'powerbi-users': 'Power BI Full',
    'powerbi-users-light': 'Power Bi Light',
    'salesforce-seats': 'Salesforce',
    'sforce-seats-total': 'Salesforce',
    'zendesk-seats-total': 'Zendesk',
    'zendesk-agents': 'Zendesk',
    'm365-seats': 'Microsoft 365 Full',
    'm365-seats-light': 'Microsoft 365 Light',
    'o365-mailboxes': 'Exchange mailboxes',
    'o365-onedrives': 'OneDrive users',
    'sharepoint-users': 'SharePoint users',
    'o365-group-users': 'Groups & Teams users',
    'gsites-users': 'Google Sites',
    'gsuite-gdrives': 'Google Drive',
    'gsuite-mailboxes': 'Gmail',
    'confluence-users': 'Confluence users',
    'miro-users': 'Miro users',
    'jira-users': 'Jira users',
    'bamboohr-users': 'BambooHR users',
    'docusign-users': 'DocuSign users',
    'okta-users': 'Okta users',
    'confluence-seats-total': 'Confluence',
    'jira-seats-total': 'Jira',
    'bamboohr-seats-total': 'BambooHR',
    'docusign-seats-total': 'DocuSign',
    'okta-seats-total': 'Okta',
    'miro-seats-total': 'Miro'
};

/** Reverse map: resource name → connector key */
export const resourceToConnectorMap: Record<string, string> = Object.entries(usageResourcesMap)
    .reduce<Record<string, string>>((acc, [connector, resources]) => {
        for (const resource of resources) {
            acc[resource] = connector;
        }
        return acc;
    }, {});
